rasterizer:
	g++ -O3 -o rasterizer Camera.cpp Color.cpp Helpers.cpp Main.cpp Matrix4.cpp Mesh.cpp Rotation.cpp Scaling.cpp Scene.cpp tinyxml2.cpp Translation.cpp Triangle.cpp Vec3.cpp Vec4.cpp -std=c++11
